### ISSUE TITLE
Couldn't get it to work (Foundry Version 10 Build 291), possible fix. 

### ISSUE THREAD

**Issue by TemeFi** [dmdorman/foundryvtt-custom-ruler#1]
I couldn't get the module to work, so after tinkering around, I found that changing 
`id: CustomRuler.id` in `class CustomRulerForm extends FormApplication`, 
to `id: CustomRuler.ID `worked

**Comment by dmdorman** [comment]
thanks for reporting! should be fixed now

**Comment by buktaoneye** [comment]
Selecting "Add New Ruler" in _Build 315 Version 11 Stable_ presents this console error:
```
main.js:263  Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'undefined')
    at CustomRulerForm._handleButtonClick (main.js:263:88)
    at HTMLFormElement.dispatch (jquery.min.js:2:43184)
    at y.handle (jquery.min.js:2:41168)
```
